language: scala
scala:
- 2.10.4
- 2.11.5
sudo: false
script: sbt clean coverage test
after_success: sbt coveralls
addons:
  postgresql: '9.3'
before_script:
- rm project/pgp.sbt && rm project/sbt-updates.sbt && rm project/sonatype.sbt && rm build.sbt
- psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
- psql -c "CREATE DATABASE scalikejdbc;" -U postgres
- psql -c "CREATE DATABASE scalikejdbc2;" -U postgres
- mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;'
  -uroot
- mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa
env:
  global:
    secure: uD3eBk5OAXJPsTSLxJudTidbmxfDRiRuBm5snX/bTC4cA+22cjA8sWCi3+o5k/pwbofz3oi5CRouvm3xaaAlk9x9EDzR2PBh7m/sxyPRmWTl6NlLFQ24Xu6jUVCmwYoqvGsieJEouTXUwumL1OJxPQXjFUVLqS322hFzggYSE2U=
